# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 44f8b0dc9f37d9b5f3bde00ae814c436f90c5f50486cd78ba584c7eff6dd3911bf04ab7dd2fda9c269ab584af19b040005473bdf7bc529ea7d3746e6b29a4b70

test:
  secret_key_base: ba93b94888f7ea2c4a5f1bbbcbd8811d7759ac895c498d4b0f92f8aa52be96ca7345c9d7095131098aaf5e37a6e3c0fb23b50d9251476212c57e5a022b66a152

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
